"""add audit_logs

Revision ID: 1aac3457ef38
Revises: 20260615_0002
Create Date: 2026-06-16 09:37:42.338681
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1aac3457ef38'
down_revision: Union[str, None] = '20260615_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
