"""baseline: core tables

These tables predate Alembic in this repo — they were only ever created by
`Base.metadata.create_all`, so a fresh database had no way to reach the current
schema. This revision is inserted at the root of the chain: databases already
stamped at a later revision skip it, fresh ones now build correctly.

Revision ID: 20260101_0000
Revises: (none — chain root)
Create Date: 2026-08-26 14:32:20.072880
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20260101_0000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.String(), nullable=True),
    sa.Column('beleg', sa.String(), nullable=True),
    sa.Column('rechnung', sa.String(), nullable=True),
    sa.Column('beschreibung', sa.String(), nullable=True),
    sa.Column('kt_soll', sa.String(), nullable=True),
    sa.Column('kt_haben', sa.String(), nullable=True),
    sa.Column('betrag', sa.Float(), nullable=True),
    sa.Column('mwst_code', sa.String(), nullable=True),
    sa.Column('mwst_pct', sa.String(), nullable=True),
    sa.Column('mwst_amount', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('classifier_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('model_blob', sa.LargeBinary(), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.Column('cv_accuracy', sa.Float(), nullable=True),
    sa.Column('train_accuracy', sa.Float(), nullable=True),
    sa.Column('sklearn_version', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_models_tenant_id'), 'classifier_models', ['tenant_id'], unique=True)
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('original_soll', sa.String(length=20), nullable=False),
    sa.Column('original_haben', sa.String(length=20), nullable=False),
    sa.Column('corrected_soll', sa.String(length=20), nullable=False),
    sa.Column('corrected_haben', sa.String(length=20), nullable=False),
    sa.Column('corrected_mwst_code', sa.String(length=10), nullable=False),
    sa.Column('corrected_mwst_pct', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_tenant_id'), 'corrections', ['tenant_id'], unique=False)
    op.create_table('kontenplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('konto_nr', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kontenplan_id'), 'kontenplan', ['id'], unique=False)
    op.create_index(op.f('ix_kontenplan_tenant_id'), 'kontenplan', ['tenant_id'], unique=False)
    op.create_table('konto_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('konto_soll', sa.String(), nullable=False),
    sa.Column('konto_haben', sa.String(), nullable=False),
    sa.Column('mwst_code', sa.String(), nullable=False),
    sa.Column('mwst_pct', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_konto_defaults_id'), 'konto_defaults', ['id'], unique=False)
    op.create_index(op.f('ix_konto_defaults_tenant_id'), 'konto_defaults', ['tenant_id'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lookup_key', sa.String(length=500), nullable=False),
    sa.Column('kt_soll', sa.String(length=20), nullable=False),
    sa.Column('kt_haben', sa.String(length=20), nullable=False),
    sa.Column('mwst_code', sa.String(length=10), nullable=False),
    sa.Column('mwst_pct', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lookup_key', name='uq_tenant_memory')
    )
    op.create_index(op.f('ix_memory_tenant_id'), 'memory', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_memory_tenant_id'), table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_konto_defaults_tenant_id'), table_name='konto_defaults')
    op.drop_index(op.f('ix_konto_defaults_id'), table_name='konto_defaults')
    op.drop_table('konto_defaults')
    op.drop_index(op.f('ix_kontenplan_tenant_id'), table_name='kontenplan')
    op.drop_index(op.f('ix_kontenplan_id'), table_name='kontenplan')
    op.drop_table('kontenplan')
    op.drop_index(op.f('ix_corrections_tenant_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_classifier_models_tenant_id'), table_name='classifier_models')
    op.drop_table('classifier_models')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('tenants')
    # ### end Alembic commands ###
