#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# lib/todo.sh — backlog engine
#   - scans code for tech debt (auto P0/P1)
#   - parses manual seed (scripts/backlog.seed.md)
#   - renders scripts/TODO.md and scripts/AI_CONTEXT.md
#
# Designed to be sourced. No top-level side effects.
# Override any path/threshold via env before sourcing.
# ─────────────────────────────────────────────────────────

: "${SCRIPT_DIR:=scripts}"
: "${BACKEND:=backend/app}"
: "${FRONT:=frontend/src}"
: "${SEED_FILE:=$SCRIPT_DIR/backlog.seed.md}"
: "${TODO_FILE:=$SCRIPT_DIR/TODO.md}"
: "${AI_CONTEXT_FILE:=$SCRIPT_DIR/AI_CONTEXT.md}"

# Colors are optional; guard so the lib works standalone.
: "${GREEN:=$'\033[32m'}"; : "${YELLOW:=$'\033[33m'}"
: "${RED:=$'\033[31m'}";   : "${DIM:=$'\033[2m'}"
: "${BOLD:=$'\033[1m'}";   : "${RESET:=$'\033[0m'}"

# Optional roadmap bridge. Populated by roadmap.sh via:
#   export ROADMAP_SUMMARY="V3 6 6\nV4 6 6\n..."
: "${ROADMAP_SUMMARY:=}"

# ── Auto debt rules ──────────────────────────────────────
# Each rule: "PRIORITY|label|test command". If the command SUCCEEDS,
# the item is considered an open debt and added to the auto backlog.
# Add a new rule = add one line. That is the whole extension surface.
_debt_rules() {
  cat <<'RULES'
P0|Hardcoded Ollama URL still present|grep -rq "localhost:11434" backend/app/services --include="*.py" 2>/dev/null
P0|TODO/FIXME markers left in backend|grep -rIlq "TODO\|FIXME" backend/app --include="*.py" 2>/dev/null
P0|TODO/FIXME markers left in frontend|grep -rIlq "TODO\|FIXME" frontend/src --include="*.tsx" --include="*.ts" 2>/dev/null
P1|No backend Dockerfile|! test -f backend/Dockerfile
P1|No CI workflow|! ls .github/workflows/*.yml >/dev/null 2>&1
P1|No backend tests directory|! test -d backend/tests
P1|No lint config (ruff)|! { test -f .pre-commit-config.yaml || grep -rqi ruff pyproject.toml 2>/dev/null; }
P1|No global error boundary|! test -f frontend/src/components/shared/ErrorBoundary.tsx
P1|No billing router (V6)|! test -f backend/app/routers/billing.py
RULES
}

# Returns matched auto items as "PRIORITY\tlabel"
collect_auto_debt() {
  local prio label cmd
  _debt_rules | while IFS='|' read -r prio label cmd; do
    [ -z "$prio" ] && continue
    if eval "$cmd" >/dev/null 2>&1; then
      printf '%s\t%s\n' "$prio" "$label"
    fi
  done
}

# Returns manual items as "STATUS\tTAG\tdescription"  (STATUS = OPEN | DONE)
parse_backlog() {
  [ -f "$SEED_FILE" ] || return 0
  local line status tag desc
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|\#*) continue ;;
    esac
    status="OPEN"
    case "$line" in
      x\ *|X\ *) status="DONE"; line="${line#? }" ;;
    esac
    if printf '%s' "$line" | grep -q '^\[[^]]*\]'; then
      tag="$(printf '%s' "$line" | sed -E 's/^\[([^]]*)\].*/\1/')"
      desc="$(printf '%s' "$line" | sed -E 's/^\[[^]]*\][[:space:]]*//')"
    else
      tag="NOTE"; desc="$line"
    fi
    printf '%s\t%s\t%s\n' "$status" "$tag" "$desc"
  done < "$SEED_FILE"
}

_counts() {
  AUTO_OPEN="$(collect_auto_debt | wc -l | tr -d ' ')"
  MANUAL_OPEN="$(parse_backlog | grep -c '^OPEN' || true)"
  MANUAL_DONE="$(parse_backlog | grep -c '^DONE' || true)"
}

# ── Roadmap bridge ───────────────────────────────────────
# ROADMAP_SUMMARY holds newline-separated "V D T" lines (captured from
# roadmap.sh's ROADMAP_DATA markers). Empty when run without roadmap data.
_render_roadmap_block() {
  [ -n "$ROADMAP_SUMMARY" ] || { echo "- (run via roadmap.sh for version %)"; return; }
  printf '%s\n' "$ROADMAP_SUMMARY" | while read -r v d t; do
    [ -z "$v" ] && continue
    local pct=$(( t > 0 ? d * 100 / t : 0 ))
    echo "- \`$v\` $d/$t ($pct%)"
  done
}

# ── Render TODO.md ───────────────────────────────────────
render_todo() {
  local now; now="$(date '+%Y-%m-%d %H:%M')"
  {
    echo "# TODO — Buchhaltung"
    echo
    echo "> Auto-generated by \`project-overview.sh\` on $now."
    echo "> Manual tasks live in \`backlog.seed.md\` — edit there, not here."
    echo

    echo "## 🔴 Auto-detected (code scan)"
    echo
    local prio label found=0
    for prio in P0 P1; do
      while IFS=$'\t' read -r p label; do
        [ "$p" = "$prio" ] || continue
        echo "- [ ] \`$p\` $label"
        found=1
      done < <(collect_auto_debt)
    done
    [ "$found" -eq 0 ] && echo "- ✅ No automated tech debt detected."
    echo

    echo "## 📋 Manual backlog (you / client / CTO)"
    echo
    local status tag desc open=0
    while IFS=$'\t' read -r status tag desc; do
      [ "$status" = "OPEN" ] || continue
      echo "- [ ] \`[$tag]\` $desc"
      open=1
    done < <(parse_backlog)
    [ "$open" -eq 0 ] && echo "- _No open manual tasks._"
    echo

    echo "## ✅ Done"
    echo
    local done=0
    while IFS=$'\t' read -r status tag desc; do
      [ "$status" = "DONE" ] || continue
      echo "- [x] \`[$tag]\` $desc"
      done=1
    done < <(parse_backlog)
    [ "$done" -eq 0 ] && echo "- _Nothing closed yet._"
  } > "$TODO_FILE"
}

# ── Render AI_CONTEXT.md ─────────────────────────────────
render_ai_context() {
  local now; now="$(date '+%Y-%m-%d %H:%M')"
  _counts
  {
    echo "# AI_CONTEXT — Buchhaltung"
    echo
    echo "> Auto-generated $now. Feed this to an AI agent before code tasks."
    echo
    echo "## §8 CTO Protocol"
    echo
    echo "- Multi-tenant SaaS: every query must filter by \`tenant_id\`."
    echo "- Stack: FastAPI + asyncpg + SQLAlchemy, Next.js, PostgreSQL, Ollama."
    echo "- Open auto-debt items: **$AUTO_OPEN**"
    echo "- Open manual tasks: **$MANUAL_OPEN** | Done: **$MANUAL_DONE**"
    echo "- Priority order: resolve all \`P0\` before shipping new features."
    echo
    echo "## §9 Live Backlog Snapshot"
    echo
    echo "### Auto-detected"
    local p label any=0
    while IFS=$'\t' read -r p label; do
      echo "- \`$p\` $label"; any=1
    done < <(collect_auto_debt)
    [ "$any" -eq 0 ] && echo "- (clean)"
    echo
    echo "### Manual (open)"
    local status tag desc m=0
    while IFS=$'\t' read -r status tag desc; do
      [ "$status" = "OPEN" ] || continue
      echo "- \`[$tag]\` $desc"; m=1
    done < <(parse_backlog)
    [ "$m" -eq 0 ] && echo "- (none)"
    echo
    echo "### Roadmap progress"
    _render_roadmap_block
  } > "$AI_CONTEXT_FILE"
}

# ── Terminal section for project-overview.sh ─────────────
print_backlog_section() {
  _counts
  echo "${BOLD}Backlog${RESET}"
  local prio label shown=0
  for prio in P0 P1; do
    while IFS=$'\t' read -r p label; do
      [ "$p" = "$prio" ] || continue
      local c=$RED; [ "$p" = "P1" ] && c=$YELLOW
      printf "  ${c}● %-3s${RESET} %s\n" "$p" "$label"
      shown=1
    done < <(collect_auto_debt)
  done
  [ "$shown" -eq 0 ] && echo "  ${GREEN}● No auto-detected debt${RESET}"
  printf "  ${DIM}Manual: %s open, %s done — seed: %s${RESET}\n" \
    "$MANUAL_OPEN" "$MANUAL_DONE" "$SEED_FILE"
  echo
}

# Regenerate both derived files. Called by project-overview.sh / roadmap.sh.
sync_backlog_files() {
  [ -f "$SEED_FILE" ] || cat > "$SEED_FILE" <<'SEED'
# Backlog Seed — manual tasks (you / client / CTO)
# Format: [TAG] description   |   mark done with leading "x "
SEED
  render_todo
  render_ai_context
}

# ── Frontend version sync ────────────────────────────────
# Writes the current shipped roadmap version to a generated TS constant.
# sidebar.tsx imports APP_VERSION from here, so the badge auto-updates.
: "${ROADMAP_VERSION:=}"
: "${FE_DIR:=frontend/src}"
: "${VERSION_FILE:=$FE_DIR/lib/version.ts}"

sync_frontend_version() {
  [ -n "$ROADMAP_VERSION" ] || return 0
  [ -d "$(dirname "$VERSION_FILE")" ] || return 0
  cat > "$VERSION_FILE" <<EOF
// AUTO-GENERATED by scripts/roadmap.sh — do not edit by hand.
// Reflects the highest fully-completed roadmap version.
export const APP_VERSION = "${ROADMAP_VERSION}";
EOF
}
