#!/usr/bin/env bash
# Regenerate scripts/AI_CONTEXT.md — a live, machine-readable map of the repo so
# an AI agent (or a new dev) gets accurate context without guessing.
# Run: make ai-context
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/scripts/AI_CONTEXT.md"
cd "$ROOT"

py() { python3 "$@"; }

{
  echo "# AI_CONTEXT — generated repo map"
  echo
  echo "> Generated by \`make ai-context\` on $(date -u '+%Y-%m-%d %H:%M UTC'). Do not edit by hand."
  echo "> Conventions and rules live in [AGENTS.md](../AGENTS.md); this file is only the *map*."
  echo
  echo "## Snapshot"
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| Commit | \`$(git rev-parse --short HEAD 2>/dev/null || echo n/a)\` on \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo n/a)\` |"
  echo "| Backend Python files | $(find backend/app -name '*.py' | wc -l | tr -d ' ') |"
  echo "| Backend lines | $(find backend/app -name '*.py' -exec cat {} + | wc -l | tr -d ' ') |"
  echo "| Frontend TS/TSX files | $(find frontend/src -name '*.ts' -o -name '*.tsx' | wc -l | tr -d ' ') |"
  echo "| Frontend lines | $(find frontend/src \( -name '*.ts' -o -name '*.tsx' \) -exec cat {} + | wc -l | tr -d ' ') |"
  echo "| Migrations | $(ls backend/alembic/versions/*.py 2>/dev/null | wc -l | tr -d ' ') |"
  echo "| Backend tests | $(grep -rhoE '^(async )?def test_[a-z0-9_]+' backend/tests 2>/dev/null | wc -l | tr -d ' ') |"
  echo

  echo "## HTTP routes"
  echo
  echo "| Method | Path | Handler | File |"
  echo "|---|---|---|---|"
  py - <<'PY'
import pathlib, re

# Prefixes applied at include time in main.py (e.g. auth is mounted at /api/auth).
main = pathlib.Path("backend/app/main.py").read_text()
include_prefix = {}
for im in re.finditer(r'include_router\(\s*(?:\w+ as )?(\w+)(?:_router)?\.router\s*,\s*prefix\s*=\s*["\']([^"\']+)["\']', main):
    include_prefix[im.group(1)] = im.group(2)

for f in sorted(pathlib.Path("backend/app/routers").glob("*.py")):
    src = f.read_text()
    prefix = include_prefix.get(f.stem, "")
    m = re.search(r'APIRouter\((?:[^)]*?)prefix\s*=\s*["\']([^"\']*)["\']', src, re.S)
    if m:
        prefix += m.group(1)
    for rm in re.finditer(r'@router\.(get|post|put|patch|delete)\(\s*["\']([^"\']*)["\']', src):
        method, path = rm.group(1).upper(), rm.group(2)
        rest = src[rm.end():]
        fn = re.search(r'\n(?:async )?def (\w+)', rest)
        print(f"| `{method}` | `{prefix}{path}` | `{fn.group(1) if fn else '?'}` | `{f.as_posix()}` |")
PY
  echo

  echo "## Database models"
  echo
  echo "| Model | Table | Tenant-scoped | Columns | File |"
  echo "|---|---|---|---|---|"
  py - <<'PY'
import pathlib, re
for f in sorted(pathlib.Path("backend/app/models").glob("*.py")):
    src = f.read_text()
    for cm in re.finditer(r'class (\w+)\(([^)]*)\):(.*?)(?=\nclass |\Z)', src, re.S):
        name, bases, body = cm.group(1), cm.group(2), cm.group(3)
        if "Base" not in bases or name == "Base":
            continue
        table = re.search(r'__tablename__\s*=\s*["\']([^"\']+)["\']', body)
        cols = re.findall(r'\n    (\w+)\s*[:=][^=]', body)
        cols = [c for c in cols if not c.startswith("__")]
        scoped = "yes" if "tenant_id" in cols else "—"
        print(f"| `{name}` | `{table.group(1) if table else '?'}` | {scoped} | {len(cols)} | `{f.as_posix()}` |")
PY
  echo

  echo "## Services (business logic)"
  echo
  echo "| Module | Public entry points | Lines |"
  echo "|---|---|---|"
  py - <<'PY'
import pathlib, re
paths = sorted(list(pathlib.Path("backend/app/services").rglob("*.py")))
for f in paths:
    if f.name == "__init__.py":
        continue
    src = f.read_text()
    names = re.findall(r'\n(?:async )?def ([a-z]\w*)\(', src) + re.findall(r'\nclass (\w+)', src)
    names = [n for n in names if not n.startswith("_")][:6]
    print(f"| `{f.as_posix()}` | {', '.join('`'+n+'`' for n in names) or '—'} | {len(src.splitlines())} |")
PY
  echo

  echo "## Frontend routes"
  echo
  echo "| Route | File | Lines |"
  echo "|---|---|---|"
  py - <<'PY'
import pathlib
for f in sorted(pathlib.Path("frontend/src/app").rglob("page.tsx")):
    route = "/" + f.parent.relative_to("frontend/src/app").as_posix()
    route = "/" if route == "/." else route
    print(f"| `{route}` | `{f.as_posix()}` | {len(f.read_text().splitlines())} |")
PY
  echo

  echo "## Frontend state stores & shared libs"
  echo
  py - <<'PY'
import pathlib, re
for f in sorted(pathlib.Path("frontend/src/lib").glob("*.ts*")):
    if f.name == "api-types.ts":
        print(f"- `{f.as_posix()}` — **generated** from the OpenAPI schema (`make api-types`)")
        continue
    exports = re.findall(r'export (?:const|function|type|interface) (\w+)', f.read_text())[:8]
    print(f"- `{f.as_posix()}` — {', '.join('`'+e+'`' for e in exports) or 'no named exports'}")
PY
  echo

  echo "## Biggest files (refactor candidates)"
  echo
  echo '```'
  find backend/app frontend/src -type f \( -name '*.py' -o -name '*.tsx' -o -name '*.ts' \) \
    ! -name 'api-types.ts' -exec wc -l {} + | sort -rn | sed -n '2,11p'
  echo '```'
} > "$OUT"

echo "✔ $OUT"
