#!/usr/bin/env bash
# Write STATUS.md at the repo root: one page of numbers about the codebase.
# Run via `make status`. Pure grep/ls — no venv, node, or network required.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/STATUS.md"

count_matches() { # count_matches <regex> <path...>
  local pattern="$1"; shift
  grep -rEh "$pattern" "$@" 2>/dev/null | wc -l | tr -d ' '
}
count_files() { # count_files <dir> <find-name-pattern>
  find "$1" -type f -name "$2" 2>/dev/null | wc -l | tr -d ' '
}

# ── Version ──────────────────────────────────────────────────────────────────
VERSION="$(grep -Eo 'APP_VERSION: str = "[^"]+"' backend/app/core/config.py | grep -Eo '[0-9][^"]*' || true)"
VERSION="${VERSION:-unknown}"

# ── Backend ──────────────────────────────────────────────────────────────────
BACKEND_TESTS="$(count_matches '^\s*(async )?def test_' backend/tests)"
BACKEND_TEST_FILES="$(count_files backend/tests 'test_*.py')"
ROUTER_FILES="$(find backend/app/routers -maxdepth 1 -name '*.py' ! -name '__init__.py' | wc -l | tr -d ' ')"
ROUTES="$(count_matches '^\s*@router\.(get|post|put|patch|delete)\(' backend/app/routers)"
MODELS="$(count_matches '^class \w+\(Base\)' backend/app/models)"

# ── Alembic ──────────────────────────────────────────────────────────────────
MIGRATIONS="$(find backend/alembic/versions -maxdepth 1 -name '*.py' ! -name '__init__.py' | wc -l | tr -d ' ')"
alembic_head_from_files() {
  # The head is the revision no other file names as its down_revision.
  local revs downs r
  revs="$(grep -rhoE '^revision(: str)? = ["'"'"'][^"'"'"']+' backend/alembic/versions | sed -E 's/.*= ["'"'"']//')"
  downs="$(grep -rhoE '^down_revision(: [^=]+)? = ["'"'"'][^"'"'"']+' backend/alembic/versions | sed -E 's/.*= ["'"'"']//')"
  for r in $revs; do
    grep -qx "$r" <<<"$downs" || printf '%s\n' "$r"
  done
}
ALEMBIC_HEAD=""
if [[ -x backend/venv/bin/python ]]; then
  ALEMBIC_HEAD="$( (cd backend && "$ROOT/backend/venv/bin/python" -m alembic heads 2>/dev/null) | awk '{print $1}' | tr '\n' ' ' | sed 's/ *$//')" || true
fi
if [[ -z "$ALEMBIC_HEAD" ]]; then
  ALEMBIC_HEAD="$(alembic_head_from_files | tr '\n' ' ' | sed 's/ *$//')"
fi
ALEMBIC_HEAD="${ALEMBIC_HEAD:-unknown}"

# ── Frontend ─────────────────────────────────────────────────────────────────
VITEST_FILES="$(find frontend/src -type f \( -name '*.test.ts' -o -name '*.test.tsx' \) | wc -l | tr -d ' ')"
VITEST_TESTS="$(find frontend/src -type f \( -name '*.test.ts' -o -name '*.test.tsx' \) -print0 \
  | xargs -0 grep -Eh '^\s*(it|test)(\.each\([^)]*\))?\(' 2>/dev/null | wc -l | tr -d ' ')"
E2E_SPECS="$(count_files frontend/e2e '*.spec.ts')"

# ── Roadmap ──────────────────────────────────────────────────────────────────
# An item may wrap onto indented continuation lines; fold them back into one line.
OPEN_ITEMS="$(awk '
  /^- \[ \] \*\*B-[0-9]+\*\*/ { if (item != "") print item; item = $0; next }
  item != "" && /^[[:space:]]+[^[:space:]]/ { sub(/^[[:space:]]+/, " "); item = item $0; next }
  { if (item != "") print item; item = "" }
  END { if (item != "") print item }
' ROADMAP.md)"
OPEN_COUNT="$( { [[ -n "$OPEN_ITEMS" ]] && printf '%s\n' "$OPEN_ITEMS"; } | wc -l | tr -d ' ')"
DONE_COUNT="$(grep -cE '^- \*\*B-[0-9]+\*\* ✅' ROADMAP.md || true)"
DONE_COUNT="${DONE_COUNT:-0}"

open_table() {
  [[ -n "$OPEN_ITEMS" ]] || { echo "_none_"; return; }
  local bt='`'
  echo "| ID | Item | Sev / Effort |"
  echo "|----|------|--------------|"
  # "- [ ] **B-xx** Title. — `S` / `M`"  →  "| B-xx | Title. | S / M |"
  printf '%s\n' "$OPEN_ITEMS" | sed -E \
    -e "s/^- \[ \] \*\*(B-[0-9]+)\*\* (.*) — ${bt}([A-Z])${bt} \/ ${bt}([A-Z])${bt} *\$/| \1 | \2 | \3 \/ \4 |/" \
    -e 't' \
    -e 's/^- \[ \] \*\*(B-[0-9]+)\*\* (.*)$/| \1 | \2 | – |/'
}

# ── Git ──────────────────────────────────────────────────────────────────────
DATE="$(date -u +%Y-%m-%d)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

# ── Write ────────────────────────────────────────────────────────────────────
{
  echo "# STATUS — Buchhaltung"
  echo
  echo "> Generated by \`make status\` (\`scripts/status.sh\`) — do not edit by hand."
  echo "> $DATE · \`$BRANCH\` @ \`$COMMIT\` · app version **$VERSION**"
  echo
  echo "## Numbers"
  echo
  echo "| Area | Count |"
  echo "|------|-------|"
  echo "| Backend tests (\`def test_\`) | $BACKEND_TESTS in $BACKEND_TEST_FILES files |"
  echo "| Frontend unit tests (vitest) | $VITEST_TESTS in $VITEST_FILES files |"
  echo "| E2E specs (Playwright) | $E2E_SPECS |"
  echo "| API routers / routes | $ROUTER_FILES / $ROUTES |"
  echo "| ORM models | $MODELS |"
  echo "| Alembic migrations | $MIGRATIONS (head: \`$ALEMBIC_HEAD\`) |"
  echo "| Roadmap B-xx open / done | $OPEN_COUNT / $DONE_COUNT |"
  echo
  echo "## Open roadmap items"
  echo
  open_table
  echo
  echo "See \`ROADMAP.md\` for order and context."
} > "$OUT"

echo "✔ $OUT ($BACKEND_TESTS backend tests · $ROUTES routes · $OPEN_COUNT open B-xx)"
