/* eslint-disable */
/**
 * AUTO-GENERATED — do not edit by hand.
 * Source: backend FastAPI OpenAPI schema.
 * Regenerate with: make api-types  (or: npm run gen:api)
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Chat
         * @description Stream a grounded chat answer as Server-Sent Events.
         */
        post: operations["ai_chat_api_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ai Status
         * @description Report whether the tenant's Ollama is reachable and which model is used.
         */
        get: operations["ai_status_api_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Summary
         * @description Return a non-streaming monthly summary.
         */
        post: operations["ai_summary_api_ai_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_audit__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_api_bookings__get"];
        put?: never;
        /** Create Bookings */
        post: operations["create_bookings_api_bookings__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Booking Stats */
        get: operations["booking_stats_api_bookings_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify Transaction */
        post: operations["classify_transaction_api_classify__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Classify */
        post: operations["batch_classify_api_classify_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Correction */
        post: operations["log_correction_api_classify_correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corrections */
        get: operations["list_corrections_api_classify_corrections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/download/{dtype}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_classify_download__dtype__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classifier Info */
        get: operations["classifier_info_api_classify_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory */
        get: operations["list_memory_api_classify_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_classify_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/top-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Classes */
        get: operations["top_classes_api_classify_top_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Model */
        post: operations["train_model_api_classify_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Bundle */
        post: operations["upload_bundle_api_classify_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classify/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Action */
        delete: operations["delete_action_api_classify__action__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/banana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Banana */
        get: operations["export_banana_api_export_banana_get"];
        put?: never;
        /** Export Banana Post */
        post: operations["export_banana_post_api_export_banana_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_export_csv_get"];
        put?: never;
        /** Export Csv Post */
        post: operations["export_csv_post_api_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Email */
        post: operations["send_email_api_export_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/email/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Email With Rows */
        post: operations["send_email_with_rows_api_export_email_rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Excel */
        get: operations["export_excel_api_export_excel_get"];
        put?: never;
        /** Export Excel Post */
        post: operations["export_excel_post_api_export_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Detail */
        get: operations["health_detail_api_health_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/banana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Banana File
         * @description Import a Banana Buchhaltung XLS export as training data.
         *
         *     - replace: if True, delete existing training data first
         *     - also_memory: if True, also populate memory table for exact matches
         *     - auto_train: if True, retrain model after import
         */
        post: operations["import_banana_file_api_import_banana_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/banana-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Banana Text
         * @description Import from raw paste text (the paste-6.txt tab-separated format).
         */
        post: operations["import_banana_text_api_import_banana_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kontenplan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kontenplan */
        get: operations["get_kontenplan_api_kontenplan__get"];
        /** Update Kontenplan */
        put: operations["update_kontenplan_api_kontenplan__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kontenplan/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Defaults */
        get: operations["get_defaults_api_kontenplan_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pdf/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Pdf */
        post: operations["parse_pdf_api_pdf_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending */
        get: operations["list_pending_api_review__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{item_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Item */
        post: operations["approve_item_api_review__item_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{item_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Item */
        post: operations["reject_item_api_review__item_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scanner Config */
        get: operations["get_scanner_config_api_scanner_config_get"];
        /** Update Scanner Config */
        put: operations["update_scanner_config_api_scanner_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Scanner Config */
        patch: operations["update_scanner_config_api_scanner_config_patch"];
        trace?: never;
    };
    "/api/scanner/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Invoice Endpoint */
        post: operations["extract_invoice_endpoint_api_scanner_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scanner Status */
        get: operations["scanner_status_api_scanner_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scanner/vision-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vision Status */
        get: operations["vision_status_api_scanner_vision_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Learning Stats
         * @description Aggregated stats for Lernverlauf charts.
         */
        get: operations["learning_stats_api_stats_learning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Corrected Haben */
            corrected_haben?: string | null;
            /** Corrected Mwst Code */
            corrected_mwst_code?: string | null;
            /** Corrected Mwst Pct */
            corrected_mwst_pct?: string | null;
            /** Corrected Soll */
            corrected_soll?: string | null;
        };
        /** BatchRequest */
        BatchRequest: {
            /** Transactions */
            transactions: {
                [key: string]: unknown;
            }[];
        };
        /** Body_extract_invoice_endpoint_api_scanner_extract_post */
        Body_extract_invoice_endpoint_api_scanner_extract_post: {
            /** File */
            file: string;
            /**
             * Model
             * @default
             */
            model: string;
        };
        /** Body_import_banana_file_api_import_banana_post */
        Body_import_banana_file_api_import_banana_post: {
            /** File */
            file: string;
        };
        /** Body_parse_pdf_api_pdf_parse_post */
        Body_parse_pdf_api_pdf_parse_post: {
            /** File */
            file: string;
        };
        /** Body_upload_bundle_api_classify_upload_post */
        Body_upload_bundle_api_classify_upload_post: {
            /** File */
            file: string;
        };
        /** BookingCreate */
        BookingCreate: {
            /**
             * Beleg
             * @default
             */
            beleg: string;
            /**
             * Beschreibung
             * @default
             */
            beschreibung: string;
            /**
             * Betrag
             * @default 0
             */
            betrag: number;
            /**
             * Datum
             * @default
             */
            datum: string;
            /**
             * Kt Haben
             * @default
             */
            kt_haben: string;
            /**
             * Kt Soll
             * @default
             */
            kt_soll: string;
            /**
             * Mwst Amount
             * @default 0
             */
            mwst_amount: number;
            /**
             * Mwst Code
             * @default
             */
            mwst_code: string;
            /**
             * Mwst Pct
             * @default
             */
            mwst_pct: string;
            /**
             * Rechnung
             * @default
             */
            rechnung: string;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /** BuchungRowExport */
        BuchungRowExport: {
            /** Artbetrag */
            artbetrag: string;
            /** Beleg */
            beleg: string;
            /** Beschreibung */
            beschreibung: string;
            /** Betrag */
            betrag: number;
            /** Datum */
            datum: string;
            /** Ks3 */
            ks3: string;
            /** Kt Haben */
            kt_haben: string;
            /** Kt Soll */
            kt_soll: string;
            /** Mwstchf */
            mwstchf: number | string;
            /** Mwstcode */
            mwstcode: string;
            /** Mwstpct */
            mwstpct: string;
            /** Nr */
            nr: number;
            /** Rechnung */
            rechnung: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /** Beschreibung */
            beschreibung: string;
            /**
             * Betrag
             * @default 0
             */
            betrag: number;
            /**
             * Is Credit
             * @default false
             */
            is_credit: boolean;
        };
        /** CorrectRequest */
        CorrectRequest: {
            /** Beschreibung */
            beschreibung: string;
            /** Corrected Haben */
            corrected_haben: string;
            /**
             * Corrected Mwst Code
             * @default
             */
            corrected_mwst_code: string;
            /**
             * Corrected Mwst Pct
             * @default
             */
            corrected_mwst_pct: string;
            /** Corrected Soll */
            corrected_soll: string;
            /**
             * Original Haben
             * @default
             */
            original_haben: string;
            /**
             * Original Soll
             * @default
             */
            original_soll: string;
        };
        /** EmailRequest */
        EmailRequest: {
            /** Source */
            source?: string | null;
            /**
             * Subject
             * @default
             */
            subject: string;
            /** To Email */
            to_email: string;
        };
        /** EmailWithRowsRequest */
        EmailWithRowsRequest: {
            /** Rows */
            rows: components["schemas"]["BuchungRowExport"][];
            /**
             * Subject
             * @default
             */
            subject: string;
            /** To Email */
            to_email: string;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Rows */
            rows: components["schemas"]["BuchungRowExport"][];
        };
        /** ExtractedInvoice */
        ExtractedInvoice: {
            /** Classification Confidence */
            classification_confidence?: number | null;
            /** Classification Input */
            classification_input?: string | null;
            /** Classification Source */
            classification_source?: string | null;
            /**
             * Custom Ocr Available
             * @default false
             */
            custom_ocr_available: boolean;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Invoice Number
             * @default
             */
            invoice_number: string;
            /** Kt Haben */
            kt_haben?: string | null;
            /** Kt Soll */
            kt_soll?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["ExtractedLineItem"][];
            /** Mwst Amount */
            mwst_amount?: number | null;
            /** Mwst Code */
            mwst_code?: string | null;
            /** Mwst Pct */
            mwst_pct?: string | null;
            /**
             * Net Amount
             * @default 0
             */
            net_amount: number | null;
            /** Ocr Provider */
            ocr_provider?: string | null;
            /**
             * Ocr Worked
             * @default false
             */
            ocr_worked: boolean;
            /** Scanner Attempts */
            scanner_attempts?: components["schemas"]["ScannerAttempt"][];
            /** Scanner Providers */
            scanner_providers?: components["schemas"]["ScannerProviderInfo"][];
            /** Scanner Steps */
            scanner_steps?: components["schemas"]["ScannerEventStep"][];
            /**
             * Total Amount
             * @default 0
             */
            total_amount: number | null;
            /**
             * Vat Amount
             * @default 0
             */
            vat_amount: number | null;
            /**
             * Vat Rate
             * @default 0
             */
            vat_rate: number | null;
            /**
             * Vendor
             * @default
             */
            vendor: string;
            /** Vision Model */
            vision_model?: string | null;
        };
        /** ExtractedLineItem */
        ExtractedLineItem: {
            /** Amount */
            amount: number;
            /** Item */
            item: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KontenplanUpdate */
        KontenplanUpdate: {
            /** Kontenplan */
            kontenplan: {
                [key: string]: string;
            };
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PredictRequest */
        PredictRequest: {
            /** Beschreibung */
            beschreibung: string;
            /**
             * Betrag
             * @default 100
             */
            betrag: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Tenant Name
             * @default Meine Firma
             */
            tenant_name: string;
        };
        /** ScannerAttempt */
        ScannerAttempt: {
            /** Available */
            available?: boolean | null;
            /** Index */
            index?: number | null;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "done" | "failed" | "pending";
        };
        /** ScannerEventStep */
        ScannerEventStep: {
            /** Confidence */
            confidence?: number | null;
            /** Icon */
            icon: string;
            /** Label */
            label: string;
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "done" | "failed" | "pending";
        };
        /** ScannerExtractResponse */
        ScannerExtractResponse: {
            data: components["schemas"]["ExtractedInvoice"];
        };
        /** ScannerModelInfo */
        ScannerModelInfo: {
            /** Available */
            available?: boolean | null;
            /** Kind */
            kind?: string | null;
            /** Name */
            name: string;
            /** Provider */
            provider?: string | null;
            /** Status Label */
            status_label?: string | null;
            /** Working */
            working?: boolean | null;
        };
        /** ScannerPipelineInfo */
        ScannerPipelineInfo: {
            /** Available */
            available?: boolean | null;
            /** Kind */
            kind?: string | null;
            /** Models */
            models?: string[];
            /** Name */
            name?: string | null;
            /** Status Label */
            status_label?: string | null;
            /** Step */
            step: number;
            /** Type */
            type: string;
        };
        /** ScannerProviderInfo */
        ScannerProviderInfo: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** ScannerStatusResponse */
        ScannerStatusResponse: {
            /** Best Vision */
            best_vision?: string | null;
            /**
             * Custom Ocr Available
             * @default false
             */
            custom_ocr_available: boolean;
            /** Error */
            error?: string | null;
            /** Models */
            models?: components["schemas"]["ScannerModelInfo"][];
            /** Ok */
            ok: boolean;
            /** Pipeline */
            pipeline?: components["schemas"]["ScannerPipelineInfo"][];
            /** Scanner Mode */
            scanner_mode?: string | null;
            /** Vision Models */
            vision_models?: string[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Role */
            role: string;
            /**
             * Subscription Plan
             * @default free
             */
            subscription_plan: string;
            /** Tenant Id */
            tenant_id: number;
            /** Tenant Name */
            tenant_name: string;
            /** Tenant Slug */
            tenant_slug?: string | null;
            /** Trial Ends At */
            trial_ends_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ScannerConfigResponse */
        app__schemas__scanner__ScannerConfigResponse: {
            /** Auto Classification Enabled */
            auto_classification_enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Ollama Model */
            default_ollama_model?: string | null;
            /** Fallback Provider */
            fallback_provider?: string | null;
            /** Invoice Matching Enabled */
            invoice_matching_enabled: boolean;
            /** Ocr Command */
            ocr_command?: string | null;
            /** Ocr Provider */
            ocr_provider: string;
            /** Ollama Base Url */
            ollama_base_url: string;
            /** Pdf Ocr Enabled */
            pdf_ocr_enabled: boolean;
            /** Tenant Id */
            tenant_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vision Provider */
            vision_provider: string;
        };
        /** ScannerConfigUpdate */
        app__schemas__scanner__ScannerConfigUpdate: {
            /**
             * Auto Classification Enabled
             * @default true
             */
            auto_classification_enabled: boolean;
            /** Default Ollama Model */
            default_ollama_model?: string | null;
            /** Fallback Provider */
            fallback_provider?: string | null;
            /**
             * Invoice Matching Enabled
             * @default true
             */
            invoice_matching_enabled: boolean;
            /** Ocr Command */
            ocr_command?: string | null;
            /** Ocr Provider */
            ocr_provider: string;
            /** Ollama Base Url */
            ollama_base_url: string;
            /**
             * Pdf Ocr Enabled
             * @default true
             */
            pdf_ocr_enabled: boolean;
            /** Vision Provider */
            vision_provider: string;
        };
        /** ScannerConfigResponse */
        app__schemas__scanner_config__ScannerConfigResponse: {
            /** Auto Classification Enabled */
            auto_classification_enabled: boolean;
            /** Default Ollama Model */
            default_ollama_model: string | null;
            /** Fallback Provider */
            fallback_provider: string | null;
            /** Invoice Matching Enabled */
            invoice_matching_enabled: boolean;
            /** Ocr Provider */
            ocr_provider: string;
            /** Ollama Base Url */
            ollama_base_url: string;
            /** Pdf Ocr Enabled */
            pdf_ocr_enabled: boolean;
            /** Review Confidence Threshold */
            review_confidence_threshold: number;
            /** Vision Provider */
            vision_provider: string;
        };
        /** ScannerConfigUpdate */
        app__schemas__scanner_config__ScannerConfigUpdate: {
            /** Auto Classification Enabled */
            auto_classification_enabled?: boolean | null;
            /** Default Ollama Model */
            default_ollama_model?: string | null;
            /** Fallback Provider */
            fallback_provider?: string | null;
            /** Invoice Matching Enabled */
            invoice_matching_enabled?: boolean | null;
            /** Ocr Provider */
            ocr_provider?: string | null;
            /** Ollama Base Url */
            ollama_base_url?: string | null;
            /** Pdf Ocr Enabled */
            pdf_ocr_enabled?: boolean | null;
            /** Review Confidence Threshold */
            review_confidence_threshold?: number | null;
            /** Vision Provider */
            vision_provider?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_chat_api_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_status_api_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ai_summary_api_ai_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_audit_api_audit__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_bookings__get: {
        parameters: {
            query?: {
                source?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bookings_api_bookings__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"] | components["schemas"]["BookingCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    booking_stats_api_bookings_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    classify_transaction_api_classify__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_classify_api_classify_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_correction_api_classify_correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_corrections_api_classify_corrections_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_classify_download__dtype__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dtype: "model" | "memory" | "bundle";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classifier_info_api_classify_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_memory_api_classify_memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    predict_api_classify_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_classes_api_classify_top_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    train_model_api_classify_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_bundle_api_classify_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_bundle_api_classify_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_action_api_classify__action__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: "memory" | "corrections" | "model";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_banana_api_export_banana_get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_banana_post_api_export_banana_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_export_csv_get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_post_api_export_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_email_api_export_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_email_with_rows_api_export_email_rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailWithRowsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_api_export_excel_get: {
        parameters: {
            query?: {
                source?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_post_api_export_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_detail_api_health_detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    import_banana_file_api_import_banana_post: {
        parameters: {
            query?: {
                replace?: boolean;
                also_memory?: boolean;
                auto_train?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_banana_file_api_import_banana_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_banana_text_api_import_banana_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kontenplan_api_kontenplan__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_kontenplan_api_kontenplan__put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KontenplanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_defaults_api_kontenplan_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    parse_pdf_api_pdf_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_pdf_api_pdf_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_api_review__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    approve_item_api_review__item_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_item_api_review__item_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scanner_config_api_scanner_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__scanner__ScannerConfigResponse"];
                };
            };
        };
    };
    update_scanner_config_api_scanner_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__scanner__ScannerConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__scanner__ScannerConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scanner_config_api_scanner_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__scanner_config__ScannerConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__scanner_config__ScannerConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_invoice_endpoint_api_scanner_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_invoice_endpoint_api_scanner_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scanner_status_api_scanner_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerStatusResponse"];
                };
            };
        };
    };
    vision_status_api_scanner_vision_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannerStatusResponse"];
                };
            };
        };
    };
    learning_stats_api_stats_learning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
